- choiminji/vending_machine/public/js/vm.js
데이터베이스 마련하였습니다.
Map으로 작업 예정입니다.
> [choiminji][#5F4B8B - 상품 등록] 등록 상품 관련 데이터베이스 - #28

- duckhee/vendingMachine/index.html
- duckhee/vendingMachine/js/main.js
- vendingMachine 생성자 함수 생성
- Product 생성자 함수 생성
하다보디 #7 이부분에 약간 진행되었어요.
`#7` 이렇게 하니깐 이슈가 자동완성처럼 나오네요?
> [Create] #06 상품 등록 추가

- duckhee/vendingMachine/js/main.js
- 소요시간 30분
- `registerProduct`는 상품등록(`Inventory`에 저장 추후 `resisterInventory`로 변경해야 될듯)
- `displayProduct`는 상품진열로 할 예정('displayInventory'에 저장)
> [duckhee][#5F4B8B - 상품 등록] 상품 등록 시 중복된 상품 있는지 확인 #7

- duckhee/vendingMachine/js/main.js
- commit 쪼개는게 아직 힘드네요 ㅠㅠ
- 상품 등록시 중복 예외처리
- 상품 삭제하기 기능 추가했어요.
> [Modified] #8 add function deleteRegisterProduct

- choiminji/vending_machine/public/index.html
- choiminji/vending_machine/public/js/vm.js
- Symbol 삭제
- Items 클래스 내 add 메서드 추가
> [choiminji][#5F4B8B - 상품 등록] 상품 등록 - #29

- duckhee/vendingMachine/js/main.js
- VendingMachine의 `addQuantity` 함수 추가했습니다.
> [duckhee][#5F4B8B - 상품 채우기] 상품 재고 추가 #10

- duckhee/vendingMachine/js/main.js
[duckhee][#5F4B8B - 상품 채우기] 재고확인 #9  
[duckhee][#5F4B8B - 상품 채우기] 재고제한 #11
> [duckhee][#5F4B8B - 상품 채우기]

- choiminji/vending_machine/public/css/style.css
- choiminji/vending_machine/public/index.html
- choiminji/vending_machine/public/js/vm.js
- 판매량 로그 `ITEM_LOG` 생성
- 상품 내역 수정 시, 관리자와 사용자 구분
- 관리자 상품 내역 수정 시 재고 0일 경우 상품 삭제
[소요시간] 3시간
> [choiminji][#5F4B8B - 상품 등록] 상품 재고 없을 경우 등록 목록에서 삭제 - #30

- choiminji/vending_machine/public/css/style.css
- choiminji/vending_machine/public/index.html
- choiminji/vending_machine/public/js/vm.js
- 관리자 측 재고량 변동 시 재고량이 0일 경우 상품 목록 삭제
- 상품별 재고량 검색 
- 상품 등록, 수정 등 재고량 변동할 때마다 재고량 표시
[소요시간] 1시간
[문제] #31, #35, #36 이슈 내용이 중복되어 함께 작업
> [choiminji][#5F4B8B - 재고 확인] - #31 #35 #36

- duckhee/vendingMachine/js/main.js
- 상품 재고 빼기(`subtractQuantity`) 추가
- [완료시간]
- 1시간
> [duckhee][#5F4B8B - 상품 빼기]

- choiminji/carousel/public/css/style.css
- choiminji/carousel/public/index.html
- choiminji/carousel/public/js/crousel.js
[완료조건] 슬라이드 생성 시, 생성자 함수 활용하여 옵션 값을 객체로 넘겨 설정한다
[소요시간] 1시간
> [choiminji][#85AF4B-실행] 매 슬라이드는 생성자 함수로 생성, 각 옵션값을 객체로 넘겨 기본값(default)과 병합 #67

- duckhee/carousel/index.html
- duckhee/carousel/src/main.js
* `obj` 객체 생성
* `Carousel` 생성자 함수 생성
* `Carousel.prototype.init`,`Carousel.prototype.render` 생성
[소요시간]
3시간
> [shldhee][#85AF4B-실행(옵션)]실행시 객체로 인자값을 전달 #91

- choiminji/carousel/public/index.html
- choiminji/carousel/public/js/crousel.js
- choiminji/carousel/public/js/ui.js
- 이미지 등록 개수 제한 : 최대 10개까지
- 이미지 추가, 삭제 기능 구현
소요시간 : 3시간
> [choiminji][#85AF4B-이미지] 이미지 개수 제한 / 추가,삭제 기능 구현 #71 #72

- choiminji/carousel/public/css/style.css
- choiminji/carousel/public/index.html
- choiminji/carousel/public/js/crousel.js
- choiminji/carousel/public/js/ui.js
- #69 옵션 값에 따라 슬라이드 너비, 높이 설정
- #70 슬라이드 기본 UI 생성
- #73  옵션 값에 따라 화살표 버튼 출력
[소요시간] 1시간
> [choiminji][#85AF4B-슬라이드] 슬라이드 UI 생성 #69 #70 #73

- duckhee/carousel/index.html
- duckhee/carousel/src/main.js
- #84 : addArrowButton 생성
- #80 : CSS 주석 작업(`.slide`) 
- #81 : `var obj` 에서 `weight, height`값 수정
> [shldhee][#85AF4B] #84 #80 #81

- duckhee/carousel/index.html
- duckhee/carousel/src/main.js
#87 : 화살표 버튼 클릭시 슬라이드 이미지 변경
#85 : mode에서 `left,center,right`로 변경
> [shldhee][#85AF4B-슬라이드]

- duckhee/carousel/src/main.js
AutoPlay 추가했습니다.
인디케이터는 못했고
리팩토링은 하는중입니다.
> [shldhee][#85AF4B-오토플레이]

- choiminji/calculator/public/css/style.css
- choiminji/calculator/public/index.html
- 연산식 출력 화면과 버튼(숫자(0~9), 연산(+, -, *, /, =), AC) 생성
- 소요시간 : 1시간
> [choiminji][#85AF4B] UI 구성 #105

- duckhee/calculator/index.html
- duckhee/calculator/src/js/calcu.js
- duckhee/calculator/src/js/calculator.js
#114 
#115 
#116 
#118 
작업 완료 후 PR날립니다.
#117 도 이번주 작업물이었는데 계산과정이 포함되어 다음주에 하기로 했어요.
> [shldhee][#85AF4B] UI 구성 #114,#115,#116,#118

- duckhee/calculator/index.html
> [Create] UI buttons

- duckhee/calculator/src/js/calculator.js
> [shldhee][#C5D5CB] 계산기 동작 #119, #120, #121

- choiminji/calculator/public/css/style.css
- choiminji/calculator/public/index.html
- choiminji/calculator/public/js/calculator.js
- 숫자/연산자 버튼 클릭 시 화면에 출력
- AC 버튼  클릭 시 화면 클리어
[소요시간] 하루 반
> [choiminji][#C5D5CB] 버튼 동작 #106 #107
